DATASET: 'pycfg.base.dairv2xt.seq4_vox04_randlat'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 10
  max_epoch: 50
  gpus: 0
  hooks: 'pycfg.base.hooks.train_hooks'
  optimizer:
    lr: 0.0002
    weight_decay: 1e-2
    betas: [0.9, 0.98]
  lr_scheduler:
    policy: 'TransformerAdaptiveScheduler'
    dim_embed: 256
    warmup_steps: 4000

TEST:
  hooks: 'pycfg.nets.streamLTS_fpvrcnn.test_hooks_dairv2xt'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.base.dairv2xt.data_manager'
  shared_modules: 'pycfg.nets.streamLTS_fpvrcnn.shared_modules_dairv2xt'
  cav_manager:
    prototype: streamLTS_collection.slcFPVRCNN
    dataset: dairv2xt
    memory_len: 4
    memory_emb_dims: 256
    memory_num_propagated: 256
    ref_pts_dim: 3
    all_grad: true

VISUALIZATION:
  output_viewer:
    plots: 'pycfg.nets.streamLTS_fpvrcnn.plots_dairv2xt'







