DATASET: 'pycfg.base.opv2v.seq1_vox04_bevmap_ego_only'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 10
  max_epoch: 51
  gpus: 0
  hooks: 'pycfg.base.hooks.train_hooks'
  optimizer:
    lr: 0.0002
    weight_decay: 1e-2
    betas: [0.9, 0.98]
  lr_scheduler:
    policy: 'MultiStepLR'
    milestones: [25, 40]
    gamma: 0.1

TEST:
  hooks: 'pycfg.nets.RLseg.test_hooks_opv2v'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.base.opv2v.data_manager'
  shared_modules: 'pycfg.nets.RLseg.shared_modules_opv2v'
  cav_manager:
    prototype: RLseg.RLsegCAV
    dataset: opv2v
#    memory_len: 4
#    memory_emb_dims: 256
#    memory_num_propagated: 256
#    ref_pts_dim: 3
    all_grad: false

VISUALIZATION:
  output_viewer:
    plots: 'pycfg.nets.RLseg.plots_opv2v'







