DATASET:
  name: opv2vt
  dataset: temporal_cosense
  meta_path: /home/yuan/data/DAIR-V2X/meta-sub-scenes
  data_path: /koko/DAIR-V2X
  enable_split_sub_folder: False  # weather has train, val or test folders
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-102.4, -41.2, -3, 102.4, 41.2, 3]
    voxel_size:  &voxel_size [0.2, 0.2, 0.2]
  batch_size_train: 1
  batch_size_test: 1
  n_workers: 4

  max_num_cavs: 7
  seq_len: &seq_len 1
  com_range: 200
  train_pipeline: 'pycfg.data_dairv2x.train_pipeline_cpu'
  test_pipeline: 'pycfg.data_dairv2x.test_pipeline_cpu'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.data_dairv2x.data_manager'
  shared_modules: {}
  cav_manager:
    prototype: base_cav.DairV2XCAV
    memory_len: *seq_len

VISUALIZATION:
  output_viewer:
    plots: []

TRAIN: {}







