DATASET:
  name: opv2vt
  dataset: temporal_cosense
  meta_path: /koko/cosense3d/opv2v_temporal_v2
  data_path: /koko/OPV2V/temporal
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-140.8, -38.4, -3, 140.8, 38.4, 3]
    voxel_size:  &voxel_size [0.2, 0.2, 0.2]
  batch_size_train: 1
  batch_size_test: 1
  n_workers: 4

  max_num_cavs: 7
  seq_len: &seq_len 1
  train_pipeline: 'pycfg.data_opv2vt_v2.pipeline_cpu'
  test_pipeline: 'pycfg.data_opv2vt_v2.pipeline_cpu'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.data_opv2vt_v2.data_manager'
  shared_modules: {}
  cav_manager:
    prototype: base_cav.OPV2VtCAV_v2
    memory_len: *seq_len

VISUALIZATION:
  output_viewer:
    plots: []







