DATASET:
  data_path_train: "/koko/LUMPI/cosense_fmt/data"
  data_path_test: "/koko/LUMPI/cosense_fmt/data"
  meta_path: "/koko/LUMPI/cosense_fmt/meta_labeled"
  visualize: false
  load_img: false
  load_lidar: true
  gt: ['bbx_center_global', 'bbx_velo_global']

  batch_size_train: 2
  batch_size_val: 4
  batch_size_test: 4
  n_workers: 4
  shuffle: true

#  voxel:
#    features: 'x,y,z,i'
#    resolution: &voxel_size [0.2, 0.2, 0.2] # name:unit [theta: deg, depth: m, zyx: m]
#    xyz_idx: &xyz_idx [0, 1, 2]
#    voxel_feature_dim: &voxel_feature_dim 8 # encoded norm features + xyz

  preprocessors:
    train:
        - GeoAugmentation
    test: []
    val: []

    GeoAugmentation:
      rotate: [0, 0, 180] # std in degree
      flip: xy # x | y | xy
      scale: 0.05
#      noise: 0.01

    CropLidarRange:
       x: [-100, 100]
       y: [-100, 100]
       z: [-3, 1]


#    NormalizeImg:
#      cams:
#        '5':
#          mean: [0.34550, 0.38377, 0.39296]
#          std: [0.24716, 0.22809, 0.21530]
#        '6':
#          mean: [0.46485, 0.48167, 0.46741]
#          std: [0.23009, 0.22193, 0.22100]
#        '7':
#          mean: [0.49440, 0.50039, 0.52180]
#          std: [0.19495, 0.17650, 0.17644]

