DATASET:
  data_path: "/koko/SingleTonTrack"
  datasets:
    lumpi:
      data_path: "/koko/LUMPI/cosense"
      meta_path: "/koko/LUMPI/cosense_metas/lumpi"
  visualize: false

  batch_size_train: 16
  batch_size_val: 4
  batch_size_test: 4
  n_workers: 4
  shuffle: true

  voxel:
    features: 'x,y,z,d,c,s,i'
    resolution: &voxel_size [ 0.1, 0.1, 0.1 ] # name:unit [theta: deg, depth: m, zyx: m]
    xyz_idx: &xyz_idx [ 0, 1, 2 ]
    voxel_feature_dim: &voxel_feature_dim 14 # encoded norm features + xyz

  preprocessors:
    train:
        - GeoAugmentation
        - CropLidarRange
        - ComposePointFeatures
        - DimensionlessCoordinates
    test: &test_pp
      - CropLidarRange
      - ComposePointFeatures
      - DimensionlessCoordinates
    val: *test_pp

    GeoAugmentation:
      rotate: [0, 0, 180] # std in degree
      flip: xy # x | y | xy
      scale: 0.05
#      noise: 0.01

    CropLidarRange:
        r: 15
        z: [ -3, 1 ]

    ComposePointFeatures:
      features: 'x,y,z,i' # t:theta, d:depth, z:height, y:euclidean centers., x:euclidean centers., c:class, i:intensity

    DimensionlessCoordinates:
      voxel_size: *voxel_size

  postprocessors: []
