MODEL:
  backbone_2d:
    backbone1:
      module_name: backbone_2d.efficient_net
      cls_name: EfficientNet
      layer_names: ['reduction_4']
      image_height: 256
      image_width: 704
    backbone2:
      module_name: backbone_2d.resnet
      cls_name: ResNet
      pretrained: 'torchvision://resnet50'
      depth: 50
      num_stages: 4
      out_indices: (2, 3)
      frozen_stages: -1
      norm_cfg:
        type: 'BN2d'
        requires_grad: False
      norm_eval: True
      with_cp: True
      style: 'pytorch'