DATASET:
  name: lumpi
  data_info: &data_info
    det_r: 75.2
    voxel_size: [0.1, 0.1, 0.1]

TRAIN:
#  project_name: 'auto-cosense3d'
  wandb_account: 'opheliayuan'
  log_every: 2
  max_epoch: 100
  gpus: 1
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  resume: true
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [50, 80]
    gamma: 0.1

MODEL:
  backbone_3d:
    - mink_unet:
        in_dim: 8
        cache: ['p4']

  submodules:
    - compression:
        data_info: *data_info
        dense: true
        planes:
          - p4:
              steps: [ 4, 2 ]
              channels: [ 64, 128, 128 ]
    - ssfa:
        data_info: *data_info
        feature_num: 128
        stride: &stride 4

  heads:
    # stage 1
    - det_center_dense:
        data_info: *data_info
        class_names: ['car', 'truck', 'bus',
                      'motorcycle', 'bicycle', 'pedestrian']
        input_channels: 128
        predict_boxes_when_training: false
        last_module: ssfa
        stride: *stride

        CLASS_AGNOSTIC: False

        CLASS_NAMES_EACH_HEAD: [
            ['car'],
            ['truck'],
            ['bus'],
#            ['barrier'],
            ['motorcycle', 'bicycle'],
            ['pedestrian'],
        ]

        SHARED_CONV_CHANNEL: 64
        USE_BIAS_BEFORE_NORM: True
        NUM_HM_CONV: 2
        separate_head_cfg:
            HEAD_ORDER: ['center', 'center_z', 'dim', 'rot']
            HEAD_DICT: {
                'center': {'out_channels': 2, 'num_conv': 2},
                'center_z': {'out_channels': 1, 'num_conv': 2},
                'dim': {'out_channels': 3, 'num_conv': 2},
                'rot': {'out_channels': 4, 'num_conv': 2},
                'dir': {'out_channels': 2, 'num_conv': 2},
#                'iou': {'out_channels': 1, 'num_conv': 2},
#                'vel': {'out_channels': 2, 'num_conv': 2},
            }

        target_assigner_config:
            NUM_MAX_OBJS: 500
            GAUSSIAN_OVERLAP: 0.1
            MIN_RADIUS: 2

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 0.25,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]
            }

        POST_PROCESSING:
            SCORE_THRESH: 0.1
            POST_CENTER_LIMIT_RANGE: [-75.2, -75.2, -10.0, 75.2, 75.2, 10.0]
            MAX_OBJ_PER_SAMPLE: 500
            NMS_CONFIG:
                NMS_TYPE: nms_gpu
                NMS_THRESH: 0.2
                NMS_PRE_MAXSIZE: 1000
                NMS_POST_MAXSIZE: 83

TEST:
  vis_function: false
  metrics:
    MetricObjDet:
      eval_func: cal_ap_all_point






