TRAIN:
#  project_name: 'auto-cosense3d'
  wandb_account: 'opheliayuan'
  log_every: 2
  max_epoch: 50
  gpus: 1
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  resume: true
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [20, 45]
    gamma: 0.1

DATASET:
  name: lucoop
  data_path: "/media/hdd/yuan/koko/data/MAPATHON/lidar0"
  meta_path: "./dataset/metas/lucoop"
  visualize: true


MODEL:
  name: 'cia_ssd'
  order: ['sparse_conv', 'm_compression', 'm_ssfa', 'h_detection']
  sparse_conv:
    in_dim: 14
    cache: ['p8']
  m_compression:
    - p8:
        steps: [ 2 ]
        channels: [ 128, 128 ]
  m_ssfa:
    feature_num: 128

  h_detection:
    # stage 1
    - s1:
        version: 'dense'
        det_r: &det_r 100
        voxel_size: &vs 0.2
        stride: 4
        in_dim: 64
        box_dim: [ 4.41, 1.98, 1.64 ]         # [l, w, h]
        box_z: 1.6                          # z of box center
        box_angles: [ 0, 90 ]                 # in degree
        iou_match: 0.4
        iou_unmatch: 0.2
        sample_size: 512



TEST:
  vis_function: false
  metrics:
    MetricStaticIou: none
    MetricDynamicIou:
      r: 100
      voxel_size: 0.2






