TRAIN:
#  project_name: 'auto-cosense3d'
  wandb_account: 'opheliayuan'
  log_every: 2
  max_epoch: 50
  gpus: 1
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  resume: true
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [20, 45]
    gamma: 0.1


DATASET:
  name: kitti
  fusion_stage: Early
  DetectionBenchmark: Detection3DpseudoAll
  data_path: "/media/hdd/yuan/koko/data/kitti"
  meta_path: "./dataset/metas/kitti"
  visualize: false

  voxel_size: &vs [0.1, 0.1, 0.1]

  preprocessors:
    GeoAugmentation:
      rotate: [ 0, 0, 10 ] # std in degree
      flip: [ 'y' ] # x | y | xy
      scale: 0.05
    CropLidarRange: &lr
      x: [0, 70.4]
      y: [-40, 40]
      z: [ -3, 1 ]

    RegisterCoordinates:
      height: -3 # register to ground height

MODEL:
  name: 'cia_ssd'
  order: ['sparse_conv', 'm_compression', 'm_ssfa', 'h_detection']

  m_compression:
    - p8:
        steps: [ 5 ]
        channels: [ 128, 128 ]

  m_ssfa:
    det_r: *lr
    voxel_size: *vs

  h_detection:
    # stage 1
    - s1:
        version: 'dense'
        det_r: *lr
        voxel_size: *vs
        stride: 8
        in_dim: 128
        target_assigner:
          name: AnchorTargetAssigner
          sample_size: 512
          assign_method: axis_aligned  # axis_aligned
          topk: 10
          box_coder:
            name: ResidualBoxCoder
          anchor_generator:
            name: AnchorGenerator
            cfg:
                car:
                  box_dim: [[3.9, 1.6, 1.56]]         # [l, w, h]
                  box_z: [1.22]                          # -1.78 + 3
                  box_angles: [ 0, 90 ]                 # in degree
                  iou_match: 0.5
                  iou_unmatch: 0.35
                cyclist:
                  box_dim: [[1.76, 0.6, 1.73]]         # [l, w, h]
                  box_z: [2.4]                          # -0.6 + 3
                  box_angles: [ 0, 90 ]                 # in degree
                  iou_match: 0.25
                  iou_unmatch: 0.1
                pedestrian:
                  box_dim: [[0.8, 0.6, 1.73]]         # [l, w, h]
                  box_z: [2.4]                          # -0.6 + 3
                  box_angles: [ 0, 90 ]                 # in degree
                  iou_match: 0.25
                  iou_unmatch: 0.1
TEST:
  vis_function: false
  metrics:
    MetricObjDet: []






