TRAIN:
#  project_name: 'auto-cosense3d'
  wandb_account: 'opheliayuan'
  log_every: 2
  max_epoch: 50
  gpus: 1
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  resume: true
  start_epoch: 17
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [20, 45]
    gamma: 0.1


DATASET:
  name: kitti
  fusion_stage: Early
  DetectionBenchmark: Detection3DpseudoAll
  data_path: "/media/hdd/yuan/koko/data/kitti"
  meta_path: "./dataset/metas/kitti"
  visualize: false

  batch_size_train: 64
  batch_size_val: 64
  batch_size_test: 32
  n_workers: 4
  shuffle: true

  voxel_size: &vs [0.1, 0.1, 0.1]

  preprocessors:
    GeoAugmentation:
      rotate: [ 0, 0, 10 ] # std in degree
      flip: [ 'y' ] # x | y | xy
      scale: 0.05
    CropLidarRange: &lr
      x: [0, 70.4]
      y: [-40, 40]
      z: [ -3, 1 ]

    RegisterCoordinates:
      height: -3 # register to ground height

MODEL:
  name: minkunet
  order: ['mink_unet', 'm_compression', 'h_detection']
  mink_unet:
    in_dim: 8
    cache: ['p4']
  m_compression:
    - p4:
        steps: [ 4, 4 ]
        channels: [ 64, 64, 64 ]

  h_detection:
    # stage 1
    - s1:
        version: 'sparse'
        det_r: *lr
        voxel_size: *vs
        stride: 4
        in_dim: 128
        # losses
        loss_cfg:
          cls:
            name: sigmoid_binary_cross_entropy
          reg:
            name: weighted_smooth_l1_loss
          scr:
            name: weighted_smooth_l1_loss
        target_assigner:
          name: AnchorTargetAssigner
          sample_size: 512
          assign_method: axis_aligned  # axis_aligned
          box_coder:
            name: ResidualBoxCoder
          anchor_generator:
            name: AnchorGenerator
            cfg:
                car:
                  box_dim: [[3.9, 1.6, 1.56]]         # [l, w, h]
                  box_z: [1.22]                          # -1.78 + 3
                  box_angles: [ 0, 90 ]                 # in degree
                  iou_match: 0.5
                  iou_unmatch: 0.35
                cyclist:
                  box_dim: [[1.76, 0.6, 1.73]]         # [l, w, h]
                  box_z: [2.4]                          # -0.6 + 3
                  box_angles: [ 0, 90 ]                 # in degree
                  iou_match: 0.25
                  iou_unmatch: 0.1
                pedestrian:
                  box_dim: [[0.8, 0.6, 1.73]]         # [l, w, h]
                  box_z: [2.4]                          # -0.6 + 3
                  box_angles: [ 0, 90 ]                 # in degree
                  iou_match: 0.25
                  iou_unmatch: 0.1
TEST:
  vis_function: false
  metrics:
    MetricObjDet:
      eval_func: cal_ap_all_point






