DATASET:
  name: none
  dataset: cosense
  data_path_train: &data_train_path "/koko/OPV2V/train"
  data_path_test: &data_test_path "/koko/OPV2V/test"
  meta_path: /koko/cosense3d/opv2v_with_speed
  DetectionBenchmark: Car
  history_len: &history_len 1
  data_info: &data_info
    lidar_range: &lidar_range [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    voxel_size: [0.2, 0.2, 0.2]
    img_size: [&h 256, &w 704]
  batch_size_train: 2
  n_workers: 4

  pipeline:
    train:
      - LoadMultiViewImages:
          root_dir: *data_train_path



TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 20
  max_epoch: 50
  gpus: 1
  log_every_n_steps: 20
  check_val_every_n_epoch: 5
  resume: true
  optimizer:
    lr: 4e-4
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [25, 40]
    gamma: 0.1
  lr_scheduler:
    policy: 'CosineAnnealingWarm'
    epochs: 50
    warmup_lr: 2e-5
    warmup_epochs: 1
    lr_min: 2e-4

MODEL:
  pre_process: []

  backbone_2d:
    backbone:
      module_name: backbone_2d.resnet
      cls_name: ResNet
      pretrained: 'torchvision://resnet50'
      depth: 50
      num_stages: 4
      out_indices: [2, 3]
      frozen_stages: -1
      norm_cfg:
        type: 'BN2d'
        requires_grad: False
      norm_eval: True
      with_cp: True
      style: 'pytorch'
    neck:
      module_name: necks_2d.cp_fpn
      cls_name: CPFPN
      in_channels: [1024, 2048]
      out_channels: 256
      num_outs: 2


  heads:
    - roi_center_img:
        name: img_roi
        num_frame_grads: 2
        num_frame_losses: 2
        skip_while_no_grad: true
        return_result: ture
    - track_query_based_cam:
        name: petr
        num_frame_grads: 2
        num_frame_losses: 2


  post_process:
    - detection_post_process:
        data_info: *data_info
        stride: 2
        visualization: true

TEST:
  metrics:
    MetricBev: []






