# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
           python-version: "3.10"

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme recommonmark ghp-import
#          pip install torch numpy

      # Building html requires all necessary dependencies be installed.
      # For cosense3d, the installation requires a lot of time,
      # therefore it is temporally built locally and copy the built html files to the gh-pages branch.

#      - name: Build HTML
#        run: |
#          cd docs/
#          make html
      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/_build/html