DATASET:
  name: nuscenes
  load_lidar: false
  load_img: true
  DetectionBenchmark: Detection3Dpseudo4WheelVehicle
  data_info: &data_info
    det_r: &r 50
    img_size: [&h 224, &w 480]

TRAIN:
#  project_name: 'auto-cosense3d'
  wandb_account: 'opheliayuan'
  log_every: 2
  max_epoch: 50
  gpus: 1
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  resume: true
  optimizer:
    lr: 4e-3
    weight_decay: 1e-7
    betas: [0.95, 0.999]
    milestones: [20, 40]
    gamma: 0.1

MODEL:
  backbone_2d:
    - efficient_net:
        model_name: efficientnet-b4
        layer_names: ['reduction_2', 'reduction_4']
        image_height: *h
        image_width: *w

  submodules:
    - encoder:
        dim: &enc_dim 128
        scale: 1.0
        middle: [2, 2]
        img_shape: [*h, *w]

        cross_view:
          heads: 4
          dim_head: 32
          qkv_bias: True
          skip: True
          no_image_features: False

          image_height: *h
          image_width: *w

        bev_embedding:
          sigma: 1.0

          bev_height: 200
          bev_width: 200
          h_meters: 100.0
          w_meters: 100.0
          offset: 0.0

          decoder_blocks: [128, 128, 64]

    - decoder:
        dim: *enc_dim
        blocks: [128, 128, 64]
        residual: True
        factor: 2

  heads:
    - bev_semseg:
        in_dim: 64
        dim_last: 64
        n_cls: 1
        outputs:
          bev: [0, 1]
          center: [1, 2]
        losses:
          cvt_loss.bev:
            weight: 1.0
            target: BinarySegmentationLoss
            args:
              gamma: 2.0
              alpha: -1.0
              min_visibility: 2
              label_indices: [[4, 5, 6, 7, 8, 10, 11]]

          cvt_loss.center:
            weight: 0.1
            target: CenterLoss
            args:
              gamma: 2.0
              min_visibility: 2


TEST:
  vis_function: false
  metrics:
    MetricObjDet:
      eval_func: cal_ap_all_point






