DATASET:
  name: lumpi
  load_lidar: false
  load_img: true
  DetectionBenchmark: Detection3Dpseudo4WheelVehicle
  data_info: &data_info
    det_r: &r 75.2
    img_size: [&h 640, &w 960]

TRAIN:
#  project_name: 'auto-cosense3d'
  wandb_account: 'opheliayuan'
  log_every: 2
  max_epoch: 100
  gpus: 1
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  resume: true
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [50, 80]
    gamma: 0.1

MODEL:
  backbone_2d:
    - efficient_net:
        model_name: efficientnet-b4
        layer_names: ['reduction_2', 'reduction_4']
        image_height: *h
        image_width: *w

  submodules:
    - encoder:
        dim: &enc_dim 128
        scale: 1.0
        middle: [2, 2]
        img_shape: [*h, *w]

        cross_view:
          heads: 4
          dim_head: 32
          qkv_bias: True
          skip: True
          no_image_features: False

          image_height: *h
          image_width: *w

        bev_embedding:
          sigma: 1.0

          bev_height: 376
          bev_width: 376
          h_meters: 150.4
          w_meters: 150.4
          offset: 0.0

          decoder_blocks: [128, 128, 64]

    - decoder:
        dim: *enc_dim
        blocks: [128, 128, 64]
        residual: True
        factor: 2

  heads:
    - bev_semseg:
        in_dim: 64
        dim_last: 64
        n_cls: 1
        outputs:
          bev: [0, 1]
          center: [1, 2]
        losses:
          cvt_loss.bev:
            weight: 1.0
            target: BinarySegmentationLoss
            args:
              gamma: 2.0
              alpha: -1.0

          cvt_loss.center:
            weight: 0.1
            target: CenterLoss
            args:
              gamma: 2.0
        target_assigner:
          data_info: *data_info
          meter_per_pixel: 0.4  # m
          assigners:
            - gaussian_center_map:
                gaussian_overlap: 0.1
                min_radius: 2
            - bev_map: []


TEST:
  vis_function: false
  metrics:
    MetricObjDet:
      eval_func: cal_ap_all_point






