DATASET:
  name: opv2v
  dataset: temporal_cosense
  meta_path: /koko/cosense3d/opv2v_full
  data_path: /koko/OPV2V
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-140.8, -38.4, -3, 140.8, 38.4, 1]
    voxel_size:  &voxel_size [0.4, 0.4, 6]
  batch_size_train: 2
  batch_size_test: 1
  n_workers: 4

  max_num_cavs: 7
  seq_len: &seq_len 1
  train_pipeline: 'pycfg.data_pipeline_lidar.pipeline_cpu'
  test_pipeline: 'pycfg.data_pipeline_lidar.pipeline_cpu'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 10
  max_epoch: 50
  gpus: 1
  resume: true
  hooks: 'pycfg.fcooper.train_hooks'
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [25, 40]
    gamma: 0.1
  lr_scheduler:
    policy: 'MultiStepLR'
    milestones: [10, 20]
    gamma: 0.1

TEST:
  hooks: 'pycfg.fcooper.test_hooks'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.data_pipeline_lidar.data_manager'
  shared_modules: 'pycfg.fcooper.shared_modules'
  cav_manager:
    prototype: lidardet_cav.LidarDetCAV
    memory_len: *seq_len
    num_grad_cav: 2

VISUALIZATION:
  output_viewer:
    plots: 'pycfg.fcooper.plots'







