DATASET:
  name: opv2v
  dataset: temporal_cosense
  meta_path: /koko/cosense3d/opv2v_full
  data_path: /koko/OPV2V
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-50, -50, -3, 50, 50, 1]
    voxel_size: &voxel_size [ 0.4, 0.4]
  drop_scenarios: ['2021_09_09_13_20_58']
  batch_size_train: 1
  n_workers: 4

  max_num_cavs: 5
  seq_len: &seq_len 1
  train_pipeline: 'pycfg.data_pipeline_cobevt.pipeline_cpu'
  test_pipeline: 'pycfg.data_pipeline_cobevt.pipeline_cpu'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 10
  max_epoch: 50
  gpus: 1
  resume: true
  hooks: 'pycfg.cobevt.train_hooks'
  optimizer:
    lr: 2e-4
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [25, 40]
    gamma: 0.1
  lr_scheduler:
    policy: 'CosineAnnealingWarm'
    epochs: 50
    warmup_lr: 2e-5
    warmup_epochs: 10
    lr_min: 5e-6

TEST:
  hooks: 'pycfg.cobevt.test_hooks'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.data_pipeline_cobevt.data_manager'
  shared_modules: 'pycfg.cobevt.shared_modules'
  cav_manager:
    prototype: img_cobevt_cav.ImgCobevtCAV
    memory_len: *seq_len
    all_grad: false

VISUALIZATION:
  output_viewer:
    plots: 'pycfg.cobevt.plots'







