DATASET:
  name: opv2v
  dataset: temporal_cosense
  meta_path: /koko/cosense3d/opv2v_full
  data_path: /koko/OPV2V
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-51.2, -38.4, -5, 51.2, 38.4, 3]
    voxel_size:  &voxel_size [0.2, 0.2, 8]
  batch_size_train: 4
  n_workers: 4

  max_num_cavs: 1
  seq_len: &seq_len 1
  train_pipeline: 'pycfg.data_pipeline_img.pipeline_cpu'
  test_pipeline: 'pycfg.data_pipeline_img.pipeline_cpu'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 10
  max_epoch: 50
  gpus: 1
  resume: true
  hooks: 'pycfg.petr.train_hooks'
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [25, 40]
    gamma: 0.1
  lr_scheduler:
    policy: 'CosineAnnealingWarm'
    epochs: 50
    warmup_lr: 2e-4
    warmup_epochs: 1
    lr_min: 2e-4

TEST:
  hooks: 'pycfg.petr.test_hooks'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.data_pipeline_img.data_manager'
  shared_modules: 'pycfg.petr.shared_modules'
  cav_manager:
    prototype: img_petr_cav.ImgPETRCAV
    memory_len: *seq_len
  forward_runner: {}

VISUALIZATION:
  output_viewer:
    plots: 'pycfg.petr.plots'









