DATASET:
  name: opv2v
  dataset: temporal_cosense
  meta_path: /koko/cosense3d/opv2v_full
  data_path: /koko/OPV2V
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-140.8, -38.4, -5, 140.8, 38.4, 3]
    voxel_size:  &voxel_size [0.2, 0.2, 8]
  batch_size_train: 1
  n_workers: 4

  max_num_cavs: 7
  seq_len: &seq_len 1
  train_pipeline: 'pycfg.data_pipeline_lidar.pipeline_cpu'
  test_pipeline: 'pycfg.data_pipeline_lidar.pipeline_cpu'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 10
  max_epoch: 50
  gpus: 1
  resume: true
  hooks: 'pycfg.mink2d_stride4_vox2_naive_lidar.train_hooks'
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [25, 40]
    gamma: 0.1
  lr_scheduler:
    policy: 'CosineAnnealingWarm'
    epochs: 50
    warmup_lr: 2e-4
    warmup_epochs: 1
    lr_min: 2e-4

TEST:
  hooks: 'pycfg.mink2d_stride4_vox2_naive_lidar.test_hooks'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.data_pipeline_lidar.data_manager'
  shared_modules: 'pycfg.mink2d_stride4_vox2_naive_lidar.shared_modules'
  cav_manager:
    prototype: base_cav.BaseCAV
    memory_len: *seq_len
  forward_runner: {}

VISUALIZATION:
  canvas_viewer:
    plots: 'pycfg.mink2d_stride4_vox2_naive_lidar.plots'







