DATASET:
  name: opv2v
  dataset: temporal_cosense
  meta_path: /koko/cosense3d/opv2v_full
  data_path: /koko/OPV2V
  DetectionBenchmark: Car
  seq_len: &seq_len 2
  data_info: &data_info
    lidar_range: &lidar_range [-102.4, -38.4, -5.0, 102.4, 38.4, 3.0]
    voxel_size:  &voxel_size [0.2, 0.2, 0.2]
  train_batch_size: 2
  n_workers: 4
  max_num_cavs: 7
  train_pipeline:
    - LoadLidarPoints: {}
    - LoadMultiViewImg: {}
    - LoadAnnotations:
        with_velocity: true
    - ResizeCropFlipRotImage:
        training: true
        data_aug_conf:
          resize_lim: [0.55, 0.7]
          final_dim: [256, 512]
          bot_pct_lim: [0.0, 0.0]
          rot_lim: [0.0, 0.0]
          H: 600
          W: 800
          rand_flip: true

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 2
  max_epoch: 50
  gpus: 1
  log_every_n_steps: 10
  check_val_every_n_epoch: 5
  resume: true
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [25, 40]
    gamma: 0.1
  lr_scheduler:
    policy: 'CosineAnnealingWarm'
    epochs: 50
    warmup_lr: 2e-5
    warmup_epochs: 1
    lr_min: 2e-4

MODEL:
  name: StreamPETR
  pre_process:
    - formatting.FormatSequenceData: {}
    - project_to_ego:
        apply_transform: false
    - transform.GlobalRotScaleTrans:
        apply_transform: true

  backbone_3d:
    - mink_unet:
        in_dim: 8
        cache: [ 'p4' ]








