DATASET:
  name: opv2v
  dataset: temporal_cosense
  meta_path: /mnt/t7/data/cosense3d/opv2v_temporal
  data_path: /mnt/t7/data/OPV2Vt/temporal
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-142, -40, -3.0, 142, 4, 1.0]
    voxel_size:  &voxel_size [0.4, 0.4, 0.4]
  batch_size_train: 1
  batch_size_test: 1
  n_workers: 4

  max_num_cavs: 7
  seq_len: &seq_len 8
  clean_seq: True
  train_pipeline: 'pycfg.streamLTS.pipeline_cpu'
  test_pipeline: 'pycfg.streamLTS.pipeline_cpu'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 1
  max_epoch: 50
  gpus: 0
  hooks: 'pycfg.streamLTS.train_hooks'
  optimizer:
    lr: 0.0002
    weight_decay: 1e-2
    betas: [0.9, 0.98]
  lr_scheduler:
    policy: 'TransformerAdaptiveScheduler'
    dim_embed: 256
    warmup_steps: 4000

TEST:
  hooks: 'pycfg.streamLTS.test_hooks'


CONTROLLER:
  num_loss_frame: 1
  batch_seq: True
  data_manager: 'pycfg.streamLTS.data_manager'
  shared_modules: 'pycfg.streamLTS.shared_modules'
  cav_manager:
    prototype: streamLTS.StreamLidarCAV
    memory_len: *seq_len
    memory_emb_dims: 256
    memory_num_propagated: 256
    ref_pts_dim: 3
    all_grad: false
    seq_len: *seq_len

VISUALIZATION:
  output_viewer:
    plots: 'pycfg.streamLTS.plots'







