DATASET:
  name: dairv2x
  dataset: temporal_cosense
  meta_path: dairv2x
  data_path: dairv2x
  enable_split_sub_folder: False
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-102.4, -41.6, -3.0, 102.4, 41.6, 1.0]
    voxel_size:  &voxel_size [0.4, 0.4, 4]
  batch_size_train: 4
  batch_size_test: 1
  n_workers: 4

  max_num_cavs: 7
  seq_len: &seq_len 4
  com_range: 200
  train_pipeline: 'pycfg.base.dairv2xt.pipeline_cpu'
  test_pipeline: 'pycfg.base.dairv2xt.pipeline_cpu'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 10
  max_epoch: 50
  gpus: 0
  hooks: 'pycfg.base.hooks.train_hooks'
  optimizer:
    lr: 0.0002
    weight_decay: 1e-2
    betas: [0.9, 0.98]
  lr_scheduler:
    policy: 'TransformerAdaptiveScheduler'
    dim_embed: 256
    warmup_steps: 4000

TEST:
  hooks: 'pycfg.streamLTS_fcooper_dairv2x.test_hooks'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.base.dairv2xt.data_manager'
  shared_modules: 'pycfg.streamLTS_fcooper_dairv2x.shared_modules'
  cav_manager:
    prototype: streamLTS_collection.slcFcooper
    dataset: dairv2x
    memory_len: *seq_len
    memory_emb_dims: 256
    memory_num_propagated: 256
    ref_pts_dim: 3
    all_grad: true

VISUALIZATION:
  output_viewer:
    plots: 'pycfg.streamLTS_fcooper_dairv2x.plots'







