DATASET:
  name: opv2v
  dataset: temporal_cosense
  meta_path: /koko/cosense3d/opv2v_full
  data_path: /koko/OPV2V
  DetectionBenchmark: Car
  data_info: &data_info
    lidar_range: [-140.8, -38.4, -3, 140.8, 38.4, 3]
    voxel_size:  &voxel_size [0.2, 0.2, 0.2]
  batch_size_train: 4
  batch_size_test: 1
  n_workers: 4

  max_num_cavs: 1
  seq_len: &seq_len 4
  train_pipeline: 'pycfg.stream_lidar.pipeline_cpu'
  test_pipeline: 'pycfg.stream_lidar.pipeline_cpu'

TRAIN:
#  project_name: 'centernet'
  wandb_account: 'opheliayuan'
  log_every: 10
  max_epoch: 50
  gpus: 1
  resume: true
  hooks: 'pycfg.stream_lidar.train_hooks'
  optimizer:
    lr: 0.001
    weight_decay: 1e-2
    betas: [0.95, 0.999]
    milestones: [25, 40]
    gamma: 0.1
  lr_scheduler:
    policy: 'CosineAnnealingWarm'
    epochs: 50
    warmup_lr: 2e-4
    warmup_epochs: 5
    lr_min: 5e-6

TEST:
  hooks: 'pycfg.stream_lidar.test_hooks'


CONTROLLER:
  num_loss_frame: 2
  data_manager: 'pycfg.stream_lidar.data_manager'
  shared_modules: 'pycfg.stream_lidar.shared_modules'
  cav_manager:
    prototype: stream_lidar.StreamLidarCAV
    memory_len: *seq_len
    memory_emb_dims: 256
    memory_num_propagated: 256
    ref_pts_dim: 3
    all_grad: true

VISUALIZATION:
  output_viewer:
    plots: 'pycfg.stream_lidar.plots'







