DATASET: 'pycfg.base.v2vreal.seq1_vox04'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.base.v2vreal.data_manager'
  shared_modules: {}
  cav_manager:
    prototype: base_cav.OPV2VtCAV
    memory_len: 1

VISUALIZATION:
  output_viewer:
    plots: []




